# Generated by Django 3.2 on 2021-04-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_moviereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
