# Generated by Django 3.2 on 2021-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_auto_20210428_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='text',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
